// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFRKP1otC6T_w_X35xMb770pCJjN3_Ds',
    appId: '1:377841965044:web:6942ddf1045955c1e04ba1',
    messagingSenderId: '377841965044',
    projectId: 'doktor-plus-2c5bf',
    authDomain: 'doktor-plus-2c5bf.firebaseapp.com',
    storageBucket: 'doktor-plus-2c5bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5N3HDibHOcUzMdwET2Gj9odX6IUcVNTo',
    appId: '1:377841965044:android:3e89f9ecee1235d8e04ba1',
    messagingSenderId: '377841965044',
    projectId: 'doktor-plus-2c5bf',
    storageBucket: 'doktor-plus-2c5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-FNzHGmTA9lq4vhP333u041ZfFengpk',
    appId: '1:377841965044:ios:11ac0b6cb40a6264e04ba1',
    messagingSenderId: '377841965044',
    projectId: 'doktor-plus-2c5bf',
    storageBucket: 'doktor-plus-2c5bf.appspot.com',
    iosBundleId: 'com.example.doktorPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-FNzHGmTA9lq4vhP333u041ZfFengpk',
    appId: '1:377841965044:ios:d9de928814664a6be04ba1',
    messagingSenderId: '377841965044',
    projectId: 'doktor-plus-2c5bf',
    storageBucket: 'doktor-plus-2c5bf.appspot.com',
    iosBundleId: 'com.example.doktorPlus.RunnerTests',
  );
}
